### ISSUE TITLE
abkhazia in docker - module abkhazia has no attribute 'utils'

### ISSUE THREAD

**Issue by antonwnk** [bootphon/abkhazia#21]
Following a successful docker build with as per [the documentation](https://coml.lscp.ens.fr/docs/abkhazia/install.html#use-in-docker) (using Docker for Windows ) running `abkhazia --help` results in the following error:
```
root@6cc56277412c:/abkhazia# abkhazia --help
Traceback (most recent call last):
  File "/usr/local/bin/abkhazia", line 11, in <module>
    load_entry_point('abkhazia==1.0', 'console_scripts', 'abkhazia')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/abkhazia-1.0-py3.6.egg/abkhazia/commands/__init__.py", line 25, in <module>
    from abkhazia.commands.abstract_command import AbstractCommand
  File "/usr/local/lib/python3.6/dist-packages/abkhazia-1.0-py3.6.egg/abkhazia/commands/abstract_command.py", line 35, in <module>
    import abkhazia.utils as utils
  File "/usr/local/lib/python3.6/dist-packages/abkhazia-1.0-py3.6.egg/abkhazia/utils/__init__.py", line 19, in <module>
    from .misc import *
  File "/usr/local/lib/python3.6/dist-packages/abkhazia-1.0-py3.6.egg/abkhazia/utils/misc.py", line 22, in <module>
    import abkhazia.utils.config as config
AttributeError: module 'abkhazia' has no attribute 'utils'
```

**Comment by mmmaat** [comment]
Hi! thanks for reporting. Indeed I replicate your issue and will come back with a fix in the next few days.

**Comment by mmmaat** [comment]
you can rebuild with the updated Dockerfile, it should work now.
